version: "3.8"
services:
    app:
        build:
          args:
            user: loja
            uid: 1000
          context: ./
          dockerfile: Dockerfile
        image: loja
        container_name: loja-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks:
          - loja
    db:
        image: mysql:5.7
        container_name: loja-db
        restart: unless-stopped        
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql       
        volumes:
            - ./docker-compose/mysql:/var/lib/mysql
            
        ports:
            - 3388:3306
        networks:
            - loja
    nginx:
        image: nginx:1.17-alpine
        container_name: loja-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - loja

networks:
  loja:
    driver: bridge